// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.887
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"teamforger/backend/core"
)

func Base(isLoggedIn bool, user core.User, content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>TeamForger</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css\"><style>\n\t\t\tbody {\n\t\t\t\tbackground: linear-gradient(135deg, #6a11cb 0%, #2575fc 100%);\n\t\t\t\tmin-height: 100vh;\n\t\t\t\tcolor: #333;\n\t\t\t}\n\t\t\t.card {\n\t\t\t\tborder-radius: 15px;\n\t\t\t\tbox-shadow: 0 10px 20px rgba(0,0,0,0.1);\n\t\t\t\tborder: none;\n\t\t\t}\n\t\t\t.btn-primary {\n\t\t\t\tbackground: linear-gradient(to right, #6a11cb, #2575fc);\n\t\t\t\tborder: none;\n\t\t\t}\n\t\t\t.navbar {\n\t\t\t\tbackground: rgba(255, 255, 255, 0.9);\n\t\t\t\tbackdrop-filter: blur(10px);\n\t\t\t\tbox-shadow: 0 2px 10px rgba(0,0,0,0.1);\n\t\t\t}\n\t\t\t.form-control:focus {\n\t\t\t\tborder-color: #6a11cb;\n\t\t\t\tbox-shadow: 0 0 0 0.25rem rgba(106, 17, 203, 0.25);\n\t\t\t}\n\t\t</style></head><body><nav class=\"navbar navbar-expand-lg navbar-light\"><div class=\"container\"><a class=\"navbar-brand fw-bold text-primary\" href=\"/\"><i class=\"bi bi-people-fill me-2\"></i>TeamForger</a><div class=\"collapse navbar-collapse\"><ul class=\"navbar-nav ms-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isLoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li class=\"nav-item\"><a class=\"nav-link\" href=\"/home\"><i class=\"bi bi-house-door me-1\"></i>Home</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"/signout\"><i class=\"bi bi-box-arrow-right me-1\"></i>Sign Out</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<li class=\"nav-item\"><a class=\"nav-link\" href=\"/signin\"><i class=\"bi bi-box-arrow-in-right me-1\"></i>Sign In</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"/signup\"><i class=\"bi bi-person-plus me-1\"></i>Sign Up</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</ul></div></div></nav><main class=\"container py-5\"><div class=\"row justify-content-center\"><div class=\"col-md-8 col-lg-6\"><div class=\"card p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div></div></main><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
